### ISSUE TITLE
Would it be possible to automatically enable the certs?

### ISSUE THREAD

**Issue by kklas** [ADVTOOLS/ADVTrustStore#11]
Hello,

Thanks for this amazing tool! It saved me a lot of time configuring multiple simulators.

I was wondering why is it necessary to manually enable each cert in the Settings app? Is there a way to go around this?

There must be a file somewhere on the system where these cert settings are getting persisted, and changing this file would enable the certs automatically. I couldn't locate it in the sim udid folder (~/Library/Developer/CoreSimulator/Devices/\<udid\>/).

Would such a feature be possible?

**Comment by hotbott** [comment]
Automatic enabling the certs would be awesome 😻

**Comment by andrivet** [comment]
Don’t think it is possible
