### ISSUE TITLE
Run with python3 will get error: invalid decimal literal

### ISSUE THREAD

**Issue by afeiship** [ADVTOOLS/ADVTrustStore#21]
My default python env is python3:
```shell
/usr/bin/env python
# Python 3.10.0
```
Maybe this should be work:
```python
/usr/bin/env python2
```

This is my errors:
```shell
❯ ./iosCertTrustManager.py -t ./TrustStore.sqlite3 -e ~/foo.crt
  File "/xxx/Downloads/ADVTrustStore-master/./iosCertTrustManager.py", line 281
    length = 0L
             ^
SyntaxError: invalid decimal literal
```

**Comment by andrivet** [comment]
This is not compatible with Python 3

**Comment by aekoch** [comment]
Is there a fundamental reason that this is not compatible with Python 3?  Python 2 is well beyond end of life at this point.

**Comment by andrivet** [comment]
“ Is there a fundamental reason that this is not compatible with Python 3?” no
“ Python 2 is well beyond end of life at this point.” yes

**Comment by EmilAlipiev** [comment]
@aekoch by any chance could you fix that?
