### ISSUE TITLE
Unable to install certificates using Xcode 7.1

### ISSUE THREAD

**Issue by kerrmarin** [ADVTOOLS/ADVTrustStore#7]
Hi there.

After running the script to install my CA in iOS 9.1/8.4 it seems to not successfully install the certificate. The script reports back success, but navigating to Settings in the simulator doesn't show any profiles installed. Is this a known issue?

I can install the CA certificate by dragging and dropping it into the simulator.

**Comment by daniel-c** [comment]
The script installs the CA in the truststore database which is not visible in Settings, but which affects any app connecting in HTTPS. When you drop the CA in the simulator it is not installed in the truststore database and it will not change the behaviour of apps connecting with https: the connection to a server using a self-signed CA will fail unless you install the CA with the script.

**Comment by kerrmarin** [comment]
Hi Daniel, thanks for your reply. Unfortunately, I've found the opposite to be true -- using this script does indeed add a row to the TrustStore sqlite DB but it still does not allow connections (on iOS 8.4 & iOS 9.1, haven't tested other iOS versions) through HTTPS to a service with a certificate signed by a custom CA. If, however, I drag and drop the CA certificate into the simulator, and install it as a "profile", the above works fine (and dragging and dropping definitely adds a row to the TrustStore db).

It would be great to get some confirmation that this is indeed a bug in Xcode 7(.1).

**Comment by ntulele** [comment]
The script works fine for me with iOS Simulator **9.3** with a self-signed CA:  
* _pre-cert-install:_  connection from app **fails** with this error in Simulator log: `NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)`
* _post-install_ of .pem file using this python script: connection **succeeds**

Thank you, @daniel-c !!
